# E2E version of taskkit-base template
# Uses local image tag (set by e2e scripts) instead of production registry
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: taskkit-base
  namespace: argo-workflows
  labels:
    homelab-tasks.dev/category: base
    homelab-tasks.dev/runtime: taskkit
    homelab-tasks.dev/environment: e2e
  annotations:
    description: "E2E base template for taskkit tasks - uses locally built image"
spec:
  serviceAccountName: argo-workflow
  templates:
    - name: run-task
      inputs:
        parameters:
          - name: task-name
            description: "Name of the task to run (e.g., 'echo', 'http_request')"
          - name: input-json
            description: "JSON input for the task"
      outputs:
        parameters:
          - name: result
            valueFrom:
              path: /outputs/result.json
      volumes:
        - name: io
          emptyDir: {}
      initContainers:
        - name: prepare-input
          image: alpine:3.19
          command: [sh, -c]
          args:
            - |
              mkdir -p /inputs /outputs
              cat > /inputs/input.json << 'INPUTEOF'
              {{inputs.parameters.input-json}}
              INPUTEOF
              echo "Task: {{inputs.parameters.task-name}}"
              echo "Input prepared ($(wc -c < /inputs/input.json) bytes)"
              cat /inputs/input.json
          volumeMounts:
            - name: io
              mountPath: /inputs
              subPath: inputs
            - name: io
              mountPath: /outputs
              subPath: outputs
      container:
        # IMAGE_TAG is replaced by e2e/scripts/run.sh before applying
        image: taskkit:local
        imagePullPolicy: Never
        command: ["task-run", "run", "{{inputs.parameters.task-name}}"]
        args:
          - "--input"
          - "/inputs/input.json"
          - "--output"
          - "/outputs/result.json"
        volumeMounts:
          - name: io
            mountPath: /inputs
            subPath: inputs
          - name: io
            mountPath: /outputs
            subPath: outputs
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
